[cursor]
vi_mode_style = "Block"

[font]
size = 10.5

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "ToggleViMode"
# key = "A"
# mode = "Vi|~Search"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 25
y = 25

[window]
opacity = 0.75
blur = true

[scrolling]
history = 1000
multiplier = 3

[colors.primary]
background = "#11121D"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#11121D"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#11121D"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#11121D"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#11121D"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#11121D"
background = "#a6adc8"

[colors.hints.start]
foreground = "#11121D"
background = "#f9e2af"

[colors.hints.end]
foreground = "#11121D"
background = "#a6adc8"

[colors.selection]
text = "#11121D"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
